export const components = [
  {
    x: 300,
    y: 200,
    width: 20,
    height: 20,
    rotation: 0,
    fill: " #989898",
    elemId: "1",
    name: "Ноутбук",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/nout.svg",
  },

  {
    x: 300,
    y: 200,
    width: 21,
    height: 21,
    rotation: 0,
    fill: " #989898",
    elemId: "3",
    name: "Лампа",
    opacity: 0.5,
    zIndex: 51,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/lampa.svg",
  },

  {
    x: 300,
    y: 200,
    width: 20,
    height: 20,
    rotation: 0,
    fill: " #989898",
    elemId: "8",
    name: "Кофемашина",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/nout.svg",
  },

  {
    x: 300,
    y: 200,
    width: 20,
    height: 20,
    rotation: 0,
    fill: " #989898",
    elemId: "6",
    name: "Принтер",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/nout.svg",
  },

  {
    x: 100,
    y: 10,
    width: 200,
    height: 100,
    fill: " #D2D2D2",
    elemId: "100",
    name: "Стол",
    opacity: 0.6,
    zIndex: 50,
    stroke: "black", // Цвет бордера
    strokeWidth: 2, // Ширина бордера
    draggable: true,
    figure: "1",
  },

  {
    x: 300,
    y: 200,
    width: 50,
    height: 50,
    fill: "red",
    elemId: "2",
    name: "Ноутбук",
    opacity: 0.5,
    zIndex: 51,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/stul.svg",
  },
  {
    x: 100,
    y: 10,
    width: 50,
    height: 50,
    fill: "green",
    elemId: "300",
    name: "ПК",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "1",
  },

  {
    x: 100,
    y: 10,
    width: 50,
    height: 50,
    fill: "#1280ff",
    elemId: "400",
    name: "Монитор",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "1",
  },
  {
    x: 100,
    y: 10,
    width: 50,
    height: 50,
    fill: "#313131",
    elemId: "500",
    name: "Стена",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "2",
    points: [200, 200, 200, 400],
  },

  {
    x: 300,
    y: 200,
    width: 20,
    height: 12,
    fill: "red",
    elemId: "600",
    name: "Стул",
    opacity: 0.5,
    zIndex: 51,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/stul.svg",
  },
  {
    x: 300,
    y: 200,
    width: 60,
    height: 16,
    rotation: 0,
    fill: "red",
    elemId: "700",
    name: "Диван",
    opacity: 0.5,
    zIndex: 51,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/divan.svg",
  },
  {
    x: 300,
    y: 200,
    width: 30,
    height: 6,
    rotation: 0,
    fill: " #989898",
    elemId: "800",
    name: "Дверь",
    opacity: 0.5,
    zIndex: 51,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/door.svg",
  },

  {
    x: 300,
    y: 200,
    width: 300,
    height: 200,
    rotation: 0,
    fill: " #989898",
    elemId: "1000",
    name: "Кабинет",
    opacity: 0.5,
    zIndex: 51,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/com.svg",
  },
];
