export const components = [
  {
    x: 100,
    y: 10,
    width: 200,
    height: 100,
    fill: "red",
    elemId: "1",
    name: "Стол",
    opacity: 0.6,
    zIndex: 50,
    stroke: "black", // Цвет бордера
    strokeWidth: 2, // Ширина бордера
    draggable: true,
    figure: "1",
  },
  {
    x: 300,
    y: 200,
    width: 50,
    height: 50,
    fill: "red",
    elemId: "2",
    name: "Ноутбук",
    opacity: 0.5,
    zIndex: 51,
    draggable: true,
    figure: "3",
    svgPath: "/img/canvasImg/stul.svg",
  },
  {
    x: 100,
    y: 10,
    width: 50,
    height: 50,
    fill: "green",
    elemId: "3",
    name: "ПК",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "1",
  },

  {
    x: 100,
    y: 10,
    width: 50,
    height: 50,
    fill: "#1280ff",
    elemId: "4",
    name: "Монитор",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "1",
  },
  {
    x: 100,
    y: 10,
    width: 50,
    height: 50,
    fill: "#313131",
    elemId: "5",
    name: "Стена",
    opacity: 0.5,
    zIndex: 100,
    draggable: true,
    figure: "2",
    points: [200, 200, 200, 400],
  },
];
